jQuery.validator.addMethod("format",function(value,element){
		var nrule=/^\w+$/;
		return this.optional(element)||nrule.test(value);
	})
	$(document).ready(function(){
		$('#loginform').validate({
			rules:{
				username:{
					required:true,
					rangelength:[2,16],
					format:true
				},
				password:{
					required:true,
					rangelength:[2,16]
				}
			},
			messages:{
				username:{
					required:"用户名不能为空",
					rangelength:"用户名在2-16位之间",
					format:"请输入数字字母或下划线"	
				},
				password:{
					required:"密码不能为空",
					rangelength:"密码在2-16位之间"
				}
			}
		});
		$('#registerform').validate({
			rules:{
				username:{
					required:true,
					rangelength:[2,16],
					format:true
				},
				password:{
					required:true,
					rangelength:[2,16]
				},
				confirm:{
					required:true,
					rangelength:[2,16],
					equalTo:'#password'
				}

			},
			messages:{
				username:{
					required:"用户名不能为空",
					rangelength:"用户名在2-16位之间",
					format:"请输入数字字母或下划线"
				},
				password:{
					required:"密码不能为空",
					rangelength:"密码在2-16位之间"
				},
				confirm:{
					required:"密码不能为空",
					rangelength:"密码在2-16位之间",
					equalTo:"两次密码输入不一致"
				}
			}
		});
	})
